# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it /camera2/depth/points2
sensors:
  - filtered_cloud_topic: /move_group/filtered_cloud
    max_range: 5.0
    max_update_rate: 1.0
    padding_offset: 0.05
    padding_scale: 1.0
    point_cloud_topic: /head_mount_kinect/depth_registered/points
    point_subsample: 1
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
