obstacle_range: 5.5
raytrace_range: 6.0
robot_base_frame: ebot_base
footprint: [[-0.3, -0.25], [-0.3, 0.25], [0.3, 0.25], [0.3, -0.25]]
update_frequency: 3.0
publish_frequency: 1.0
transform_tolerance: 0.5
resolution: 0.05
#layers
obstacle_laser:
  observation_sources: scan
  scan: {data_type: LaserScan,clearing: true,marking: true,topic: /ebot/laser/scan,inf_is_valid: true}
inflation:
  inflation_radius: 5.3
  cost_scaling_factor: 1.0
static:
  map_topic: map
  subscribe_to_updates: true  