obstacle_range: 2.5
raytrace_range: 3.0
robot_base_frame: ebot_base
footprint: [[-0.3, -0.25], [-0.3, 0.25], [0.3, 0.25], [0.3, -0.25]]
update_frequency: 3.5
publish_frequency: 1.5
transform_tolerance: 0.5
resolution: 0.02
#layers
obstacle_laser:
  observation_sources: scan
  scan: {data_type: LaserScan,clearing: true,marking: true,topic: /ebot/laser/scan,inf_is_valid: true}
inflation:
  inflation_radius: 1.75
  cost_scaling_factor: 2.58
inflation_1:
  inflation_radius: 4.8
  cost_scaling_factor: 1.0
static:
  map_topic: map
  subscribe_to_updates: true  
