  
  global_frame: odom
  rolling_window: true
  static_map: false
  robot_base_frame: ebot_base
  width: 5.0
  height: 5.0
  update_frequency: 8.0
  publish_frequency: 1.0

  plugins:
    - {name: obstacle_laser, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_1,       type: "costmap_2d::InflationLayer"}
