  global_frame: odom
  robot_base_frame: ebot_base
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  inflation_radius: 0.09
  cost_scaling_factor: 10.0
  plugins:
    - {name: obstacle_laser, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,      type: "costmap_2d::InflationLayer"}