controller_frequency: 5.0
recovery_behaviour_enabled: true
NavfnROS:
  allow_unknown: true
  default_tolerance: 0.2
TrajectoryPlannerROS:
  max_vel_x: 2.0
  min_vel_x: 0.1
  max_vel_theta: 3.0
  min_vel_theta: -3.0
  min_in_place_vel_theta: 10.0
  acc_lim_theta: 5.0
  acc_lim_x: 5.0
  holonomic_robot: false
  escape_vel: -0.6
  
  #goal tolerance param.
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false
  
  # Forward Simulation Parameters
  sim_time: 4.0
  sim_granularity: 0.025
  angular_sim_granularity: 0.05
  vx_samples: 20
  vtheta_samples: 40

  
  #trajectory scoring param
  meter_scoring: true
  occdist_scale: 0.025
  path_distance_bias: 4.8
  goal_distance_bias: 0.25

  heading_lookahead: 0.4
  heading_scoring: true
  heading_scoring_timestep: 1.0
  dwa: true
  simple_attractor: false

  #oscillation Prevention Parameters
  oscillation_reset_dist: 0.1
  escape_reset_dist: 0.1
  escape_reset_theta: 0.2


